SEARCH_HELP_TEXT = """from:user_id
mentions:user_id
has:link/embed/file/video/image/sound/sticker
before:date (format: 2015-01-01)
after:date (format: 2015-01-01)
in:channel_id
pinned:true/false"""

COMMAND_ASSISTS = (
    ("goto <#[channel_id]> - go to specified channel/server/category/DM", "goto"),
    ("view_pfp *<@[user_id]> - view specified or selected users pfp", "view_pfp"),
    ("react *[reaction] - show prompt or react to message", "react"),
    ("status *[type] - change your status 1/online, 2/idle, 3/dnd, 4/invisible", "status"),
    ("open_link *[num] - open selected link or specify index if multiple are on same line", "open_link"),
    ("copy_link *[num] - copy selected link to clipboard or specify index if multiple are on same line", "copy_link"),
    ("download *[num] - download selected attachment", "download"),
    ("play *[num] - play selected attachment", "play"),
    ("search *[query] - prompt for message search or search provided string", "search"),
    ("gif *[query] - prompt for gif search or search provided string", "gif"),
    ("record / record cancel - start/stop/cancel recording voice message", "record"),
    ("upload *[path] - prompt to upload attachment or use provided path", "upload"),
    ("profile *<@[user_id]> - view profile of selected or specified user", "profile"),
    ("channel *<#[channel_id]> - view info of selected or specified channel", "channel"),
    ("summaries *<#[channel_id]> - view summaries of selected or specified channel", "summaries"),
    ("hide *<#[channel_id]> - view info of selected or specified channel", "hide"),
    ("toggle_mute *<#[channel_id]> - toggle mute state of selected or specified channel", "toggle_mute"),
    ("mark_as_read *<#[channel_id]> - mark selected or specified channel/server/category/DM/* as read", "mark_as_read"),
    ("mark_as_unread - mark selected message as unread", "mark_as_unread"),
    ("copy_message - copy selected message text", "copy_message"),
    ("spoil - reveal one by one spoiler in selected message", "spoil"),
    ("link_channel *<#[channel_id]> - store channel link in clipboard", "link_channel"),
    ("link_message - store selected message link in clipboard", "link_message"),
    ("goto_mention *[num] - go to channel/message mention in selected message", "goto_mention"),
    ("cancel *[download/1/upload/2/attachment/3] - cancel all downloads and/or uploads", "cancel"),
    ("external_edit - open external editor to type message in it", "external_edit"),
    ("member_list - toggle member list", "member_list"),
    ("toggle_thread - join/leave currently open thread", "toggle_thread"),
    ("toggle_thread_tree - join/leave selected thread in tree", "toggle_thread_tree"),
    ("bottom - go to chat bottom", "bottom"),
    ("goto_reply - go to message that selected message is replying to", "goto_reply"),
    ("show_reactions - show reactions details for selected message", "show_reactions"),
    ("show_pinned - show pinned messages for current channel", "show_pinned"),
    ("pin_message - pin selected message to current channel", "pin_message"),
    ("push_button [num/name] - push button on interactive app message", "push_button"),
    ("string_select [string] - select string on interactive app message", "string_select"),
    ("toggle_tab - toggle tabbed (pinned) state of current channel", "toggle_tab"),
    ("switch_tab [num/next/prev] - switch to specified tab by its number", "switch_tab"),
    ("remove_all_tabs - remove all tabbed channels", "remove_all_tabs"),
    ("vote [num] - vote for specified answer index on active poll message", "vote"),
    ("paste - paste image or file as attachment or text from clipboard", "paste"),
    ("insert_timestamp YYYY-MM-DD-HH-mm / YYYY-MM-DD / HH:mm / HH:mm:SS - insert timestamp", "insert_timestamp"),
    ("set_notifications *<#[channel_id]> ... - show and modify server/channel notification settings", "set_notifications"),
    ("check_standing - check account standing, anything non-100 is concerning", "check_standing"),
    ("custom_status [string] - set custom status text", "custom_status"),
    ("custom_status_emoji [emoji] - set custom status emoji", "custom_status_emoji"),
    ("custom_status_remove - remove custom status", "custom_status_remove"),
    ("toggle_afk - toggle afk state; if afk, mobile devices will receive notifications", "toggle_afk"),
    ("block *ignore <@[user_id]> - block/ignore user", "block"),
    ("unblock *ignore <@[user_id]> - unblock/unignore user", "unblock"),
    ("toggle_blocked_messages - toggle showing messages from blocked users in chat", "toggle_blocked_messages"),
    ("view_emoji *[emoji/num] - download specified custom emoji and show it in media player", "view_emoji"),
    ("voice_start_call - start voice call in currently open DM", "voice_start_call"),
    ("voice_accept_call - accept incoming voice call", "voice_accept_call"),
    ("voice_leave_call - leave current voice call", "voice_leave_call"),
    ("voice_reject_call - silence incoming call or cancel outgoing call", "voice_reject_call"),
    ("voice_list_call - show all call participants and their states in an updated list", "voice_list_call"),
    ("voice_toggle_mute - toggle mute state before joining a call", "voice_toggle_mute"),
    ("generate_invite *[duration] *[limit] - generate invite to current server, default is 7 days", "generate_invite"),
    ("rename_folder [name] - locally rename currently selected folder in tree", "rename_folder"),
    ("resize_extra_window [num/-1/+1] - resize extra window", "resize_extra_window"),
    ("collapse_all_except *[option] - collapse all servers in tree except specific [option]", "collapse_all_except"),
    ("tree_select *[server/channel], *[next/prev] - select next or previous server or channel in tree", "tree_select"),
    ("send_message * - see commands documentation for options", "send_message"),
    ("redraw - redraw UI if it ever gets messed up", "redraw"),
    ("check_for_updates *open - check endcord and extensions for updates and open gh release", "check_for_updates"),
    ("search_extensions - search all endcord extensions on GitHub", "search_extensions"),
    ("install_extension *[url] - install extension from specified git url or update all", "install_extension"),
    ("open_config_dir - open config directory with system file manager", "open_config_dir"),
    ("show_log - show live log", "show_log"),
    ("dump_chat - dump current chat to unique json file", "dump_chat"),
    ("dump_roles - dump current server roles to unique json file", "dump_roles"),
    ("game_detection_blacklist [game] - toggle blacklist for games detected in past 7 days", "game_detection_blacklist"),
    ("set [key] = [value] - change settings and save them.", "set"),
    ("quit - quit endcord", "quit"),
)
