# endcord - Copyright (C) 2025-2026 SparkLost. All Rights Reserved.
# Source-available under the Endcord License. See LICENSE for terms.
# Redistribution of modified versions is not permitted.

settings = {
    "theme": None,
    "extensions": True,
    "rpc": True,
    "game_detection": True,
    "vim_mode": False,
    "limit_chat_buffer": 100,
    "limit_channel_cache": 10,
    "download_msg": 25,
    "convert_timezone": True,
    "send_typing": True,
    "desktop_notifications": True,
    "idle_timeout": 10,
    "notification_when_focused": False,
    "remove_previous_notification": True,
    "ack_throttling": 5,
    "member_list": True,
    "member_list_auto_open": False,
    "use_nick_when_available": True,
    "remember_state": True,
    "remember_tabs": True,
    "new_tab_at_end": False,
    "reply_mention": True,
    "cache_typed": True,
    "show_pending_messages": True,
    "cursor_on_time": 0.7,
    "cursor_off_time": 0.5,
    "tab_spaces": 4,
    "blocked_mode": 2,
    "hide_spam": True,
    "keep_deleted": False,
    "limit_cache_deleted": 30,
    "max_thumb_cache_age": 7,
    "tree_show_folders": True,
    "wrap_around": True,
    "mouse": True,
    "mouse_scroll_sensitivity": 3,
    "mouse_scroll_selection": False,
    "draw_scrollbar": True,
    "screen_update_delay": 0.01,
    "extra_line_delay": 5,
    "tenor_gif_type": 1,
    "trim_embed_url_size": 40,
    "aspell_mode": "normal",
    "aspell_lang": "en_US",
    "media_mute": False,
    "media_cap_fps": 30,
    "media_font_aspect_ratio": None,
    "inline_media": True,
    "inline_media_height": 14,
    "inline_media_quality": "low",
    "rpc_external": True,
    "emoji_as_text": False,
    "message_spacing": True,
    "message_grouping": True,
    "native_media_player": False,
    "native_file_dialog": "auto",
    "save_summaries": True,
    "default_stickers": True,
    "only_one_open_server": False,
    "remember_collapsed_channels": False,
    "assist": True,
    "assist_swap_binding": True,
    "assist_skip_app_command": False,
    "fallback_keybinding_parser": False,
    "assist_limit": 50,
    "assist_score_cutoff": 15,
    "limit_command_history": 50,
    "game_detection_download_delay": 7,
    "downloads_path": None,
    "notifications_pfp": True,
    "linux_notification_sound": "message",
    "custom_notification_sound": None,
    "linux_ringtone_incoming": "phone-incoming-call",
    "custom_ringtone_incoming": None,
    "linux_ringtone_outgoing": "phone-outgoing-calling",
    "custom_ringtone_outgoing": None,
    "custom_media_player": None,
    "custom_media_blacklist": None,
    "custom_media_terminal": False,
    "custom_media_hint": False,
    "external_editor": None,
    "calls": True,
    "call_silence_threshold": -30,
    "yt_dlp_path": "yt-dlp",
    "yt_dlp_format": 18,
    "mpv_path": "mpv",
    "yt_in_mpv": False,
    "check_for_updates": 1,
    "check_update_interval": 1,
    "client_properties": "default",
    "custom_user_agent": None,
    "send_x_super_properties": True,
    "proxy": None,
    "custom_host": None,
    "capabilities": None,
    "easter_eggs": True,
    "debug": False,
}
theme = {
    "compact": False,
    "tree_width": 32,
    "extra_window_height": 6,
    "member_list_width": 20,
    "format_message": "[%timestamp] <%global_name> %app%edited\n%content",
    "format_message_grouped": " ├  %content %edited",
    "format_newline": " │  %content",
    "format_reply": " ╭──🡲 [%timestamp] <%global_name>: %content",
    "format_reactions": " ╰──⤙ %reactions",
    "format_reactions_newline": "      %reactions",
    "format_interaction": " ╭──⤙ %global_name used [%command]",
    "format_one_reaction": "[%count:%reaction]",
    "format_timestamp": "%H:%M",
    "format_status_line_l": " ⠀%status_dot %nick %warn_state %unreads %action %typing",
    "format_status_line_r": "%vim_mode %slowmode",
    "format_title_line_l": " %server: %channel_no_tab",
    "format_title_line_r": None,
    "format_subtitle_line": "─%tabs",
    "format_title_tree": " %app_name  %task",
    "format_rich": "%type %name - %state - %details",
    "format_tabs": "%name",
    "format_prompt": "[%channel] > ",
    "format_forum": "[%timestamp] - <%msg_count> - %thread_name",
    "format_forum_timestamp": "%Y-%m-%d",
    "format_search_message": "%channel: [%date] <%global_name> | %content",
    "edited_string": "(edited)",
    "app_string": "- (%app) ",
    "quote_character": "║",
    "scrollbar_character": "┃",
    "reactions_separator": " ",
    "tabs_separator": "|",
    "chat_date_separator": "─",
    "format_date": " %B %d, %Y ",
    "limit_username": 10,
    "limit_channel_name": 15,
    "limit_typing_string": 30,
    "limit_prompt": 15,
    "limit_thread_name": 0,
    "limit_tab_len": 20,
    "limit_tabs_string": 0,
    "tree_drop_down_vline": "│",
    "tree_drop_down_hline": "─",
    "tree_drop_down_intersect": "├",
    "tree_drop_down_corner": "╰",
    "tree_drop_down_pointer": "🡲",
    "tree_drop_down_thread": "⤙",
    "tree_drop_down_forum": "◆",
    "tree_drop_down_folder": "+",
    "tree_drop_down_voice": "○",
    "tree_dm_status": "●",
    "border_corners": "╭╰╮╯",
    "activity_icons": "🎮︎📺︎♪📺︎🎮︎",
    "smart_chat_lines": True,
    "username_role_colors": True,
    "dynamic_name_len": True,
    "color_default": [-1, -1],
    "color_green": [46, -1],
    "color_orange": [208, -1],
    "color_red": [196, -1],
    "color_chat_mention": [223, 234],
    "color_chat_blocked": [242, -1],
    "color_chat_deleted": [95, -1],
    "color_chat_pending": [242, -1],
    "color_chat_selected": [233, 255],
    "color_chat_separator": [242, -1, "i"],
    "color_chat_standout": [153, 234],
    "color_chat_edited": [241, -1],
    "color_chat_url": [153, -1, "u"],
    "color_chat_spoiler": [239, 239],
    "color_chat_code": [250, 233],
    "color_status_line": [233, 255],
    "color_extra_line": [233, 245],
    "color_title_line": [233, 255],
    "color_subtitle_line": [245, -1],
    "color_extra_window": [-1, -1],
    "color_extra_window_low": [245, -1],
    "color_extra_window_standout": [153, -1],
    "color_prompt": [255, -1],
    "color_input_line": [255, -1],
    "color_cursor": [233, 255],
    "color_misspelled": [222, -1],
    "color_tree_default": [255, -1],
    "color_tree_category": [153, -1],
    "color_tree_server": [153, -1],
    "color_tree_selected": [233, 255],
    "color_tree_muted": [242, -1],
    "color_tree_active": [255, 234],
    "color_tree_unseen": [-2, -2, "b"],
    "color_tree_mentioned": [197, -1],
    "color_tree_active_mentioned": [197, 234],
    "color_tree_selected_mentioned": [124, 255],
    "color_format_message": [[-1, -1], [242, -2, 0, 0, 7], [25, -2, 0, 8, 9], [25, -2, 0, 19, 20]],
    "color_format_message_grouped": [[-1, -1], [242, -2, 0, 1, 2]],
    "color_format_newline": [[-1, -1], [242, -2, 0, 1, 2]],
    "color_format_reply": [[245, -1], [242, -2, 0, 1, 5], [25, -2, 0, 14, 15], [25, -2, 0, 25, 26]],
    "color_format_reactions": [[245, -1], [242, -2, 0, 1, 5]],
    "color_format_interaction": [[245, -1], [242, -2, 0, 1, 5]],
    "color_format_forum": [[-1, -1], [242, -2, 0, 0, 12], [25, -2, 0, 15, 20]],
    "media_use_blocks": True,
    "media_truecolor": True,
    "media_ascii_palette": "  ..',;:c*loexk#O0XNW",
    "media_saturation": 1.2,
    "media_color_bg": 16,
    "media_bar_ch": "━",
}


keybindings = {
    # tree
    "tree_up": ("C-UP", 500),
    "tree_down": ("C-DOWN", 501),
    "tree_select": ("C-SPACE", 502),
    "tree_collapse_threads": ("M-h", 503),
    "tree_join_thread": ("M-j", 21),
    "channel_info": ("M-i", 25),
    "copy_channel_link": ("M-u", 30),
    # input line
    "input_left": ("LEFT", 504),
    "input_right": ("RIGHT", 505),
    "word_left": ("C-LEFT", 506),
    "word_right": ("C-RIGHT", 507),
    "select_left": ("SHIFT+LEFT", 508),
    "select_right": ("SHIFT+RIGHT", 509),
    "select_word_left": ("C-SHIFT+LEFT", 510),
    "select_word_right": ("C-SHIFT+RIGHT", 511),
    "insert_newline": ("C-n", 512),
    "undo": ("M-z", 513),
    "redo": ("M-S-z", 514),
    "select_all": ("M-a", 515),
    "copy": ("M-a", 516),
    "cut": ("M-x", 517),
    "paste": ("C-v", 23),
    "delete_word": ("C-BACKSPACE", 518),
    "delete_word_forward": ("C-DEL", 519),
    # chat
    "send_message": ("ENTER", 520),
    "chat_up": ("UP", 521),
    "chat_down": ("DOWN", 522),
    "reply":  ("C-r", 1),
    "edit": ("C-e", 2),
    "delete": ("C-d", 3),
    "toggle_ping": ("C-p", 6),
    "scroll_bottom": ("C-b", 7),
    "go_replied": ("C-g", 8),
    "download": ("C-l", 9),
    "upload": ("C-u", 13),
    "browser": ("C-o", 10),
    "view_media": ("C-w", 17),
    "spoil": ("M-s", 18),
    "search": ("C-f", 29),
    "search_gif": ("M-f", 44),
    "profile_info": ("M-p", 24),
    "copy_message_link": ("M-u", 31),
    "add_reaction": ("M-r", 36),
    "show_reactions": ("M-w", 37),
    "show_pinned": ("M-n", 43),
    # extra line
    "attach_prev": ("M-,", 14),
    "attach_next": ("M-.", 15),
    # extra window
    "extra_up": ("M-UP", 523),
    "extra_down": ("M-DOWN", 524),
    "extra_select": ("M-ENTER", 27),
    "preview_upload": ("M-v", 22),
    # media
    "media_pause": ("SPC", None),
    "media_replay": ("z", None),
    "media_seek_forward": ("RIGHT", None),
    "media_seek_backward": ("LEFT", None),
    "media_volume_up": ("UP", None),
    "media_volume_down": ("DOWN", None),
    # other
    "command_palette": ("C-/", 38),
    "cancel": ("C-x", 11),
    "cycle_status": ("M-d", 33),
    "toggle_member_list": ("M-m", 35),
    "toggle_tree": ("M-t", 32),
    "toggle_tab": ("M-t", 41),
    "switch_tab_modifier": ("M-NUM", None),
    "open_external_editor": ("M-e", 45),
    "quit": (None, 34),   # already bound to Ctrl+C
}


command_bindings = {
    "M-LEFT": "switch_tab prev",
    "M-RIGHT": "switch_tab next",
    "C-k": "command_palette; type 'goto '",
    "S-UP": "tree_select server prev; collapse_all_except selected",
    "S-DOWN": "tree_select server; collapse_all_except selected",
    "C-y UP": "resize_popup_window +1",
    "C-y DOWN": "resize_popup_window -1",
}


vim_mode_bindings = {
    # special
    "insert_mode": ("i", 525),
    # tree
    "tree_up": ("K", 500),
    "tree_down": ("J", 501),
    "tree_select": (" ", 502),
    "tree_collapse_threads": ("W", 503),
    "tree_join_thread": ("O", 21),
    "channel_info": ("I", 25),
    "copy_channel_link": ("C", 30),
    # input line
    "input_left": ("h", 504),
    "input_right": ("l", 505),
    "word_left": ("b", 506),
    "word_right": ("w", 507),
    "select_left": ("C-h", 508),
    "select_right": ("C-l", 509),
    "select_word_left": ("H", 510),
    "select_word_right": ("L", 511),
    "insert_newline": ("C-n", 512),
    "undo": ("u", 513),
    "redo": ("C-r", 514),
    "select_all": ("a", 515),
    "copy": ("y", 516),
    "cut": ("Y", 517),
    "paste": ("p", 23),
    "delete_word": ("X", 518),
    # chat
    "send_message": ("ENTER", 520),
    "chat_up": ("k", 521),
    "chat_down": ("j", 522),
    "reply": ("r", 1),
    "edit": ("e", 2),
    "delete": ("d", 3),
    "toggle_ping": ("P", 6),
    "scroll_bottom": ("B", 7),
    "go_replied": ("g", 8),
    "download": ("D", 9),
    "upload": ("U", 13),
    "browser": ("o", 10),
    "view_media": ("v", 17),
    "spoil": (18),
    "search": ("f", 29),
    "search_gif": ("F", 44),
    "profile_info": ("c", 24),
    "copy_message_link": ("M", 31),
    "add_reaction": ("R", 36),
    "show_reactions": ("A", 37),
    "show_pinned": ("n", 43),
    # extra line
    "attach_prev": ("<", 14),
    "attach_next": (">", 15),
    # extra window
    "extra_up": (",", 523),
    "extra_down": (".", 524),
    "extra_select": ("q", 27),
    "preview_upload": ("V", 22),
    # other
    "command_palette": (":", 38),
    "cancel": ("x", 11),
    "cycle_status": ("s", 33),
    "toggle_member_list": ("m", 35),
    "toggle_tree": ("t", 32),
    "toggle_tab": ("T", 41),
    "switch_tab_modifier": ("NUM", None),
    "open_external_editor": ("E", 45),
    "quit": ("Q", 34),
}

windows_override_keybindings = {
    "tree_select": ("C-a", 502),
}


macos_override_keybindings = {
    "browser": ("M-o", 10),
}


state = {
    "last_guild_id": None,
    "last_channel_id": None,
    "member_list": True,
    "tree": True,
    "collapsed": [],
    "folder_names": [],
    "tabbed_channels": [],
    "recent_channels": [],
    "favorite_emojis": [],
    "volume_out": 100,
    "volume_in": 100,
    "audio_input_device": None,
    "games_blacklist": [],
}
